### ISSUE TITLE
post-install.txt in private recipe

### ISSUE THREAD

**Issue by komik966** [moay/symfony-flex-server#10]
contents from `post-install.txt` added to private recipe does not show during `composer require`
Example public recipe with `post-install.txt`: https://github.com/symfony/recipes/tree/master/symfony/framework-bundle/3.3
Have someone tried `post-install.txt` in private recipe? Maybe I'm doing something wrong.

**Comment by moay** [comment]
We have this working properly in our demo recipes: https://github.com/moay/demo-recipes. Take a look at the rusk dummy package, there is a working `post-install.txt`.

**Comment by komik966** [comment]
ok, thanks
