### ISSUE TITLE
Error when the private recipe repo url contains port

### ISSUE THREAD

**Issue by redthor** [moay/symfony-flex-server#17]
Hi there. This is in relation to https://github.com/moay/symfony-flex-server/pull/11#issuecomment-404399159 and https://github.com/moay/symfony-flex-server/issues/13

We are using gitlab like @lainosantos but unfortunately we have to also add the Port number:

ssh://git@private-gitlab.com:5000/user/recipes.git

So our format is different again.

We are getting this error from `dashboard.js`:
```
TypeError: "n.exec(...) is null"
```
It is likely from this line: https://github.com/moay/symfony-flex-server/blob/master/assets/js/dashboard.js#L95

**Comment by moay** [comment]
Are you able to download your recipes with that url? Just messing around to get the actual problem, but I'm not able to get my recipes if I add ssh and the port to my url. Does the actual recipe resolving work for you?

**Comment by redthor** [comment]
Yes, it is pulling in our recipes. I see them in the response payload.

**Comment by moay** [comment]
I implemented an improved version of the url resolving process. It should work w/ or w/o 'ssh://', port number, '.git', and so on. Let me know if this fixes it for you. :-)
