### ISSUE TITLE
OAuth Token for Git Repo

### ISSUE THREAD

**Issue by cjsfj** [moay/symfony-flex-server#19]
I haven't tried this yet - but is there support for using an OAuth token to auth to my git repo? We use a github enterprise server in my company and prefer oauth for integrations

Thanks!

CJ

**Comment by moay** [comment]
Two thoughts:
1) Just try it. Pass Username and token via the git repo url (username:password@repo). Maybe it works. https://help.github.com/articles/git-automation-with-oauth-tokens/
2) Don't do that. Oauth tokens are personal and person based and should (imho) not be used for automated tasks where no human is involved. That's just not what they are made for and exposes the tokens to high risks. Use ssh keys for this purpose.
