### ISSUE TITLE
Server not working with the actual oficial receipe server

### ISSUE THREAD

**Issue by AlexisRossat** [moay/symfony-flex-server#20]
The paths of the receipes and maybe other things have change. So the server is not working

**Comment by moay** [comment]
I'll look into it as soon as I can. Thanks for the hint!

**Comment by AlexisRossat** [comment]
Thank you. Your work is awsome !!
We really need to have our own symfony-flex server.

**Comment by moay** [comment]
Just took a look at it. I can't find any obvious changes in either symfony flex or the recipes structure. @AlexisRossat Can you specify the problems you ran into?

**Comment by AlexisRossat** [comment]
Hi,
I did reinstall all the stuff in a new server and everything is ok. So the problem was from my side.
I'm sorry for the inconvenience

**Comment by moay** [comment]
Ok, thanks. Probably there was a change in the official repos and your local copy was not up to date or something like this. You can try running `php bin/console recipes:update` to pull the latest stuff in case something fails. If this doesn't help, `php bin/console recipes:reset` will probably solve the problems.
