### ISSUE TITLE
Recipe not downloaded for private package

### ISSUE THREAD

**Issue by Stnaire** [moay/symfony-flex-server#24]
Hi,

First of all thanks for your work.

I've carefully followed each step of the setup guide, and everything seems to work fine but when I install a private package only the composer package is downloaded but not the recipe.

So nothing related to the recipe works (bundle not added, recipe files not copied and so on).

The strange thing is that I can see the recipe in the web interface:
![list](https://i.imgur.com/342xaHr.png)

And when I do `composer require shared-storage`, the package is correctly resolved and downloaded.

But I can see that flex `auto generate` a recipe and then fails because my bundle need to copy a file in the `config/packages` to define a parameter:
```
$>composer require shared-storage
Using version dev-master for test/shared-storage-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.2.*"
Package operations: 1 install, 0 updates, 0 removals
  - Installing test/shared-storage-bundle (dev-master ca71ae3): Loading from cache
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Using "https://symfony-recipes.domain.tld" as the Symfony endpoint
Symfony operations: 1 recipe (627c70caa7d0b7771746fc4c744fb3d7)
  - Configuring test/shared-storage-bundle (>=dev-master): From auto-generated recipe
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In ArrayNode.php line 228:
!!                                                                                        
!!    The child node "project_namespace" at path "test_shared_storage" must be configured.  
!!                                                                                        
!!
!!
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json to its original content.
```

My repository is hosted on `Bitbucket`, I have a self hosted `satis` with the following configuration:

```
{
  "name": "Test Repositories",
  "homepage": "https://domain.tld",
  "repositories": [
    { "type": "vcs", "url": "https://bitbucket.org/<domain>/symfonysharedstoragebundle.git" }
  ],
  "require-all": true
}
```

In the `composer.json` of my project, I've added:
```
{
    "repositories": [ { "type": "composer", "url": "https://composer-packages.domain.tld/" } ],
    ....
}
```

Do you have any idea of what I'm missing?

Thanks

**Comment by moay** [comment]
Hi there. :-)

You'll need to tell composer to use your flex server, right now, it doesn't. See https://symfony-flex-server.readthedocs.io/en/latest/topics/setup/#using-the-server, where `https://your.domain.com` should obviously be replaced with the url to your flex server instance.

**Comment by moay** [comment]
Sorry, just saw that you already did that.

Just read a little more closely. Your flex server is reached, the recipe is downloaded and properly installed. The error that happens is `Script cache:clear returned with error code 1`, but this script is only executed after everything was done.

In the error message, it says: `The child node "project_namespace" at path "test_shared_storage" must be configured.`, which indicates that the configuration file that was installed with your flex recipe is not properly configuring all needed configuration options, there probably is a `test_shared_storage` option missing the `project_namespace` property. 

This is actually an issue with your recipe, not with the flex server.

**Comment by moay** [comment]
Okay, read again and even a little more closely. 🙄 As far as I can see, the server is reached, but does not provide a recipe for your request of installation at version dev-master. How is the version folder for your recipe named?

Explanation: The flex server will always try to use the latest recipe it finds, but never one for higher versions than the installing one. As versions are compared following semver strictly, your version folder name will need to be a semver lower than dev-master (or exactly dev-master).

Does this explanation help?

**Comment by Stnaire** [comment]
Yes it helped a lot, thank you!

You were right the name of the version folder on the recipes repository was wrong. I had put `1.0` temporarily while experimenting and I forgot about it later on.

Changing the name of the folder to `dev-master` made everything work like a charm :)

Thanks again you saved me a lot of time.
