### ISSUE TITLE
Problem to install skeleton

### ISSUE THREAD

**Issue by zorang** [moay/symfony-flex-server#3]
In our company we use 3rd party Symfony skeleton (one composer.json file) to create the projects. We want to use our private recipes within it. According to this Symfony Flex server documentation we need to add the `extra.symfony.endpoint` line to our 3rd party Symofiny composer.json file:

```
    ...
    "extra": {
        "symfony": {
            "id": "...",
            "allow-contrib": true,
            "endpoint": "http://127.0.0.1:8000/"
        }
    }
    ...
```

**If we do that and if we try to run `composer install` after that, the automated composer install symfony command is not able to create the Symfony project and this is the output from the terminal:**

```
...
  - Installing symfony/cache (v4.0.6): Loading from cache
  - Installing symfony/framework-bundle (v4.0.6): Loading from cache
  - Installing symfony/yaml (v4.0.6): Loading from cache
  - Installing symfony/dotenv (v4.0.6): Loading from cache
Writing lock file
Generating autoload files
Warning: Accessing 127.0.0.1 over http which is an insecure protocol.
Symfony operations: 4 recipes (e75591840502e826575dba2ec6bef69f)
  - Configuring symfony/flex (>=1.0): From private:master

                              
  [ErrorException]            
  Undefined index: .env.dist  
```

Our full 3rd party Symfony skeleton composer is absolutely identical to official https://github.com/symfony/skeleton/blob/4.0/composer.json except `"secure-http": false` and `"endpoint": "http://127.0.0.1:8000/"` are added. Here is a full 3rd party Symfony composer.json content:

```
{
    "name": "symfony/skeleton",
    "type": "project",
    "license": "MIT",
    "description": "A minimal Symfony project recommended to create bare bones applications",
    "require": {
        "php": "^7.1.3",
        "ext-iconv": "*",
        "symfony/console": "^4.0",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^4.0",
        "symfony/lts": "^4@dev",
        "symfony/yaml": "^4.0"
    },
    "require-dev": {
        "symfony/dotenv": "^4.0"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true,
        "secure-http": false
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": [
        ],
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "id": "01C9Q7VP048YH419WJT1WZSMH5",
            "allow-contrib": false,
            "endpoint": "http://127.0.0.1:8000/"
        }
    }
}
```
We are not able to install custom Symfony skeleton with `composer install` by using the private Flex server within it.

**Comment by moay** [comment]
Hi there. Thanks for reporting the issue, let's see if we can work this out.

First of all I think that the error report is not very declarative. Could you try to run the `composer create` command in verbose mode? This will (I hope) provide much more precise information on where and why flex can't resolve the .env.dist file.

There are several possible issues that could cause the problem. I assume you are using the mirroring functionality of the server and have a local copy of the official recipes repo. Quick checks:
- Did you download the repo? Did this download go perfectly well? Just to make sure, run `php bin/console recipes:reset`
- In case this doesn't fix the problem, could you post your output of `php bin/console server:status`?
- Just to find out whether or not the mirror is the problem, could you try to disable mirroring in order to get the official repos from the official endpoint?

**Comment by zorang** [comment]
Hi, thanks on quick answer.

Ok with this configuration it worked:

```
 ----------------------------------- ---------- 
  Proxy for official endpoint             enabled   
  Caching for official endpoint         disabled  
  Local mirror for official recipes     disabled  
  Local mirror for contrib recipes    disabled  
 ----------------------------------- ---------- 

Repo status
-----------

 ---------- --------------------------------------------------- ----------------- ------------ --------------------- 
  Repo       Url                                                 Remote readable   Downloaded   Last Update          
 ---------- --------------------------------------------------- ----------------- ------------ --------------------- 
  private    https://.....                                                                  Yes               Yes          2018-03-29 17:15:25  
  official   https://github.com/symfony/recipes                        Yes               Yes                               
  contrib    https://github.com/symfony/recipes-contrib         Yes               Yes                               
 ---------- --------------------------------------------------- ----------------- ------------ --------------------- 

```

I suppose that I should not use caching and mirroring right?

Thanks again!

**Comment by zorang** [comment]
From my side I don't have time for investigation at the moment. But great the it works without mirroring at least.
