### ISSUE TITLE
Doesn't work with private recipe repositories

### ISSUE THREAD

**Issue by 4ernovm** [moay/symfony-flex-server#8]
After running this command
```
./bin/console recipes:reset
```

I'm getting following output:
```
[ERROR] Git error: The repo url https://bitbucket.org/<user>/recipes is not readable

[OK] Official recipes repo resetted.

[OK] Contrib recipes repo resetted.
```

The only way I've managed to make it work was manually clone my repo into var/repo/private

Also it builds wrong URL if recipes are placed on bitbucket:

https://bitbucket.org/<user\>/recipes/tree/master/<user\>/<bundle\>/1.0.1/

instead of 

https://bitbucket.org/<user\>/recipes/src/master/<user\>/<bundle\>/1.0.1/

**tree** instead of **src**

**Comment by moay** [comment]
Hi there. 

Please check this:

- is your URL correct? Or does it actually contain '<user>'?
- Is your repo public? Otherwise you should try to add an ssh key to bitbucket and your flex server in order to allow access.

If both things don't help, I'll need to look deeper into it tomorrow.

Also thanks for reporting the url structure problem, I'll fix this tomorrow.

**Comment by moay** [comment]
The url structure problem will be worked on in #9

**Comment by 4ernovm** [comment]
ok. this one has been figured. repo link in git@bitbucket.org:<user\>/recipes.git format worked

**Comment by 4ernovm** [comment]
thanks for the fast feedback @moay

**Comment by moay** [comment]
This needs to be added to the docs.

**Comment by dfridrich** [comment]
Using `git@bitbucket.org:<user>/recipes.git` will broke links to recipes from dashboard. This should be fixed.

**Comment by moay** [comment]
Yes, thats #9, I'll fix this as soon as I find the time.

**Comment by moay** [comment]
Update on this one: Using `git@bitbucket.org:<user>/<repo>.git` might work, but it wasn't able to get this working. For me, using `https://bitbucket.org/<user>/<repo>` works fine. The link building issue will be updated.

**Comment by moay** [comment]
Link building should also be fixed. Thanks for reporting. 👍
